version: '3.8'

services:
  database:
    image: postgres:15
    container_name: cookbook_db
    env_file:
      - ./.env
    volumes:
      - ../Build/Database/Data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}